import 'package:flutter/material.dart';
import 'package:verso/core/design/profiles/theme_profile.dart';
import 'package:verso/core/design/profiles/verso_palette.dart';
import 'package:verso/core/design/tokens/colors.dart';
import 'package:verso/data/local/entities/user_settings.dart';

/// "Sacred Blue" — Verso's original default theme.
/// Palette values map directly to the existing [AppColors] constants so
/// existing users see no visual change when upgrading.
const ThemeProfile currentProfile = ThemeProfile(
  id: 'current',
  name: 'Sacred Blue',
  tagline: 'Deep Navy × Soft Sky × Warm Gold',
  description:
      'The original Verso palette — deep navy anchors the light mode while soft sky illuminates dark mode, paired with warm gold accents throughout.',
  inspiration: 'Classic Bible typography, sacred scripture layouts',
  light: VersoPalette(
    style: AppearanceStyle.light,
    bg: AppColors.backgroundLight,
    surface: AppColors.surfaceLight,
    surfaceAlt: AppColors.primaryContainerLight,
    border: AppColors.outlineLight,
    borderLight: AppColors.outlineVariantLight,
    primary: AppColors.primaryLight,
    primaryHover: AppColors.primaryAccentLight,
    secondary: AppColors.secondaryLight,
    accent: AppColors.primaryAccentLight,
    accentBright: AppColors.primaryHighlightLight,
    accentSoft: AppColors.primaryContainerLight,
    text: AppColors.onSurfaceLight,
    textMuted: AppColors.onSurfaceVariantLight,
    textLight: Color(0xFFADB5BD),
    success: AppColors.successLight,
    warning: Color(0xFFB86A10),
    danger: AppColors.errorLight,
    progress: AppColors.primaryLight,
    progressBg: AppColors.primaryContainerLight,
    tag: AppColors.secondaryContainerLight,
    tagText: AppColors.secondaryLight,
    streakBg: AppColors.secondaryContainerLight,
    streakText: AppColors.streakLight,
    divider: AppColors.outlineVariantLight,
    footerBg: AppColors.surfaceLight,
    footerActive: AppColors.primaryLight,
    footerInactive: AppColors.onSurfaceVariantLight,
    highlight: AppColors.primaryContainerLight,
    cross: AppColors.primaryLight,
  ),
  dark: VersoPalette(
    style: AppearanceStyle.dark,
    bg: AppColors.backgroundDark,
    surface: AppColors.surfaceDark,
    surfaceAlt: AppColors.surfaceDark,
    border: AppColors.outlineDark,
    borderLight: AppColors.outlineVariantDark,
    primary: AppColors.primaryDark,
    primaryHover: AppColors.primaryAccentDark,
    secondary: AppColors.secondaryDark,
    accent: AppColors.primaryAccentDark,
    accentBright: AppColors.primaryHighlightDark,
    accentSoft: AppColors.primaryContainerDark,
    text: AppColors.onSurfaceDark,
    textMuted: AppColors.onSurfaceVariantDark,
    textLight: Color(0xFF6B7280),
    success: AppColors.successDark,
    warning: Color(0xFFE09030),
    danger: AppColors.errorDark,
    progress: AppColors.primaryDark,
    progressBg: AppColors.primaryContainerDark,
    tag: AppColors.primaryContainerDark,
    tagText: AppColors.primaryDark,
    streakBg: AppColors.secondaryContainerDark,
    streakText: AppColors.streakDark,
    divider: AppColors.outlineVariantDark,
    footerBg: AppColors.surfaceDark,
    footerActive: AppColors.primaryDark,
    footerInactive: AppColors.onSurfaceVariantDark,
    highlight: AppColors.primaryContainerDark,
    cross: AppColors.primaryDark,
  ),
);
