import 'package:flutter/material.dart';
import 'package:verso/core/design/profiles/theme_profile.dart';
import 'package:verso/core/design/profiles/verso_palette.dart';
import 'package:verso/data/local/entities/user_settings.dart';

/// "Heritage" — Deep maroon in light, warm gold in dark.
const ThemeProfile heritageBurgundyProfile = ThemeProfile(
  id: 'heritage_burgundy',
  name: 'Heritage',
  tagline: 'Deep maroon in light, warm gold in dark',
  description:
      'A classic and sophisticated palette featuring deep maroon for light mode accents and a warm gold for dark mode.',
  inspiration: 'Classic literature and heritage design',
  light: VersoPalette(
    style: AppearanceStyle.light,
    bg: Color(0xFFFCFBFB),
    surface: Color(0xFFFFFFFF),
    surfaceAlt: Color(0xFFF9F5F5),
    border: Color(0xFFE5E0E0),
    borderLight: Color(0xFFF3EFEF),
    primary: Color(0xFF59171C),
    primaryHover: Color(0xFF451114),
    secondary: Color(0xFF822730),
    accent: Color(0xFF822730),
    accentBright: Color(0xFFA13540),
    accentSoft: Color(0xFFF7EBEB),
    text: Color(0xFF2C1E1E),
    textMuted: Color(0xFF7A6B6B),
    textLight: Color(0xFFB8AEAE),
    success: Color(0xFF22C55E),
    warning: Color(0xFFF59E0B),
    danger: Color(0xFFEF4444),
    progress: Color(0xFF59171C),
    progressBg: Color(0xFFF7EBEB),
    tag: Color(0xFFF7EBEB),
    tagText: Color(0xFF822730),
    divider: Color(0xFFE5E0E0),
    footerBg: Color(0xFFFFFFFF),
    footerActive: Color(0xFF59171C),
    footerInactive: Color(0xFF9CA3AF),
    highlight: Color(0xFFF7EBEB),
    cross: Color(0xFF59171C),
  ),
  dark: VersoPalette(
    style: AppearanceStyle.dark,
    bg: Color(0xFF141312),
    surface: Color(0xFF1C1A19),
    surfaceAlt: Color(0xFF262321),
    border: Color(0xFF3F3A37),
    borderLight: Color(0xFF2E2B29),
    primary: Color(0xFFDCB67A),
    primaryHover: Color(0xFFE8C792),
    secondary: Color(0xFFEFCC95),
    accent: Color(0xFFEFCC95),
    accentBright: Color(0xFFFCE3B6),
    accentSoft: Color(0xFF2C2418),
    text: Color(0xFFF2EAE0),
    textMuted: Color(0xFF9E958C),
    textLight: Color(0xFF6E6760),
    success: Color(0xFF22C55E),
    warning: Color(0xFFF59E0B),
    danger: Color(0xFFEF4444),
    progress: Color(0xFFDCB67A),
    progressBg: Color(0xFF362B1D),
    tag: Color(0xFF2C2418),
    tagText: Color(0xFFEFCC95),
    divider: Color(0xFF2E2B29),
    footerBg: Color(0xFF1C1A19),
    footerActive: Color(0xFFDCB67A),
    footerInactive: Color(0xFF716A62),
    highlight: Color(0xFF2C2418),
    cross: Color(0xFFDCB67A),
  ),
);
